version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=countries_db

  web:
    build: .
    command: /code/docker/start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
